language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t zhipeng/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true zhipeng/react-docker npm run test