language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t zhipeng/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true zhipeng/react-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucker_name: "elasticbeanstalk-us-west-2-xxxxxxx"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY